sudo: required

language: java

services:
  - docker
  
before_install:
- docker info
- docker run -d --name postgres -e POSTGRES_PASSWORD=moneygr -e POSTGRES_USER=moneygr -e LC_ALL=C.UTF-8 postgres
- docker run --link -p 127.0.0.1:5432:5432 postgres:postgres --rm busybox env
- docker run -v ~/.m2:/root/.m2 -v "$PWD":/usr/src -w /usr/src maven:3-jdk-8 mvn -X
- docker ps -a

script:
  - env

